### ISSUE TITLE
Error when running runComparison

### ISSUE THREAD

**Issue by Ismail-Curie** [csoneson/compcodeR#7] opened 2020-11-06 10:36 UTC
Hello,
Can you please help me with this error "Error: 'predictions' contains NA", I get this error when running runComparison.
Thank you,
Ismail

**Comment by csoneson** [comment] 2020-11-06 16:06
It is difficult to say what the issue is without more information. Could you provide a reproducible example? How do you generate your data/results?

**Comment by Ismail-Curie** [comment] 2020-11-06 17:02
Thank you, this is my example:
#data generation
generateSyntheticData("dataset1", 12500, 10, 1250,
                      repl.id = 1, seqdepth = 1e+07, minfact = 0.7, maxfact = 1.4,
                      relmeans = "auto", dispersions = "auto", fraction.upregulated = 0,
                      between.group.diffdisp = FALSE, filter.threshold.total = 1,
                      filter.threshold.mediancpm = 0, fraction.non.overdispersed = 0,
                      random.outlier.high.prob = 0, random.outlier.low.prob = 0,
                      single.outlier.high.prob = 0, single.outlier.low.prob = 0,
                      effect.size = 1.5, output.file = "SyntheticData/dataset1.rds"

#DE
mydata = "SyntheticData/dataset1.rds"

runDiffExp(data.file = mydata, result.extent = "DESeq2", 
           Rmdfunction = "DESeq2.createRmd",
           output.directory = "SyntheticData/Diffexp/", fit.type = "parametric", 
           test = "Wald", beta.prior = TRUE, 
           independent.filtering = TRUE, cooks.cutoff = TRUE, 
           impute.outliers = TRUE)

#Comparison
file.table <- data.frame(input.files = file.path("SyntheticData/Diffexp",
                                                 c("dataset1_DESeq2.rds","dataset1_EBSeq.rds")),
                        stringsAsFactors = FALSE)

checkTableConsistency(file.table)

parameters <- list(incl.nbr.samples = 10, incl.replicates = 1, incl.dataset = "dataset1",
                   incl.de.methods = NULL,
                   fdr.threshold = 0.05, tpr.threshold = 0.05, typeI.threshold = 0.05,
                   ma.threshold = 0.05, fdc.maxvar = 1500, overlap.threshold = 0.05,
                   fracsign.threshold = 0.05, mcc.threshold = 0.05,
                   nbrtpfp.threshold = 0.05,
                   comparisons = c("auc", "mcc", "fdr", "tpr", "fdrvsexpr", "typeIerror",
                                   "fracsign","nbrsign", "nbrtpfp", "correlation", "maplot","fdcurvesall",
                                   "fdcurvesone", "rocall", "rocone", "overlap", "sorensen", "scorevsoutlier",
                                   "scorevsexpr", "scorevssignal"))

runComparison(file.table = file.table, parameters = parameters, output.directory = "SyntheticData/Comparison/test/")

**Comment by csoneson** [comment] 2020-11-06 20:58
Thanks. I think I see where this is coming from. The error is thrown by `ROCR`, and I think the reason is that this package became a bit more stringent with NA values in the current version (could you confirm that you have `ROCR` version 1.0.11?). The underlying cause is that `DESeq2` generates some NA p-values when run with `cooks.cutoff = TRUE, impute.outliers = TRUE`, and these now cause `ROCR` to throw the error above. I will implement a fix for this - in the meantime, running `DESeq2` with the arguments above set to `FALSE` should work.

**Comment by csoneson** [comment] 2020-11-08 16:28
Ok, I've added a fix for this. Currently only in GitHub, should be available in Bioconductor within a couple of days too.

**Comment by Ismail-Curie** [comment] 2020-11-08 21:57
Thank you very much.

**Comment by csoneson** [comment] 2020-11-10 06:16
Changes have propagated to Bioconductor too.

**Closed by csoneson** 2020-11-10 06:16 UTC
